name: Monitor Branch Protection Changes 3
on:
  workflow_dispatch:

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            const repo = context.repo;
            
            try {
              // First get default branch
              console.log('Getting repository info...');
              const repoInfo = await github.rest.repos.get({
                owner: repo.owner,
                repo: repo.repo
              });
              
              const defaultBranch = repoInfo.data.default_branch;
              console.log(`Default branch is: ${defaultBranch}`);
              
              // Directly check protection on default branch
              console.log(`Checking protection rules for ${defaultBranch}...`);
              try {
                const protection = await github.rest.repos.getBranchProtection({
                  owner: repo.owner,
                  repo: repo.repo,
                  branch: defaultBranch
                });
                
                console.log('Protection rules found:', JSON.stringify(protection.data, null, 2));
              } catch (branchError) {
                if (branchError.status === 404) {
                  console.log(`No protection rules found for ${defaultBranch}`);
                } else {
                  throw branchError;
                }
              }
              
            } catch (error) {
              console.log('Error details:', {
                message: error.message,
                status: error.status,
                documentation_url: error.documentation_url
              });
              core.setFailed(`Error: ${error.message}`);
            }

      - name: Send Notification
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Branch Protection Rules Changed',
              body: 'Changes detected in branch protection rules. Please review the workflow logs for details.'
            });
