name: Monitor Branch Protection Changes 2
on:
  workflow_dispatch:

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            const repo = context.repo;
            
            try {
              console.log('Fetching branch protection rules...');
              const rules = await github.rest.repos.listBranchProtectionRules({
                owner: repo.owner,
                repo: repo.repo
              });
              
              console.log('Found rules:', JSON.stringify(rules.data, null, 2));
              
              // If we successfully get the rules, store them
              for (const rule of rules.data) {
                console.log(`\nProtection rule for pattern: ${rule.pattern}`);
                console.log('Settings:', {
                  'Required approvals': rule.required_pull_request_reviews?.required_approving_review_count,
                  'Dismiss stale reviews': rule.required_pull_request_reviews?.dismiss_stale_reviews,
                  'Require status checks': rule.required_status_checks?.strict,
                  'Enforce admins': rule.enforce_admins?.enabled,
                  'Allow force pushes': rule.allow_force_pushes?.enabled,
                  'Allow deletions': rule.allow_deletions?.enabled
                });
              }
              
            } catch (error) {
              console.log('Full error:', error);
              core.setFailed(`Error checking protection rules: ${error.message}`);
            }

      - name: Send Notification
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Branch Protection Rules Changed',
              body: 'Changes detected in branch protection rules. Please review the workflow logs for details.'
            });
