name: Monitor Branch Protection Changes
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Check Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo;
            
            try {
              const branches = await github.rest.repos.listBranches({
                owner: repo.owner,
                repo: repo.repo,
                protected: true
              });
              
              for (const branch of branches.data) {
                const protection = await github.rest.repos.getBranchProtection({
                  owner: repo.owner,
                  repo: repo.repo,
                  branch: branch.name
                });
                
                // Store current state in artifact for comparison
                const currentState = JSON.stringify(protection.data, null, 2);
                
                console.log(`Branch protection rules for ${branch.name}:`);
                console.log(currentState);
              }
            } catch (error) {
              core.setFailed(`Error checking branch protection: ${error.message}`);
            }

      - name: Send Notification
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Branch Protection Rules Changed',
              body: 'Changes detected in branch protection rules. Please review the workflow logs for details.'
            });
            
            // Optional: Add label to the issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              labels: ['security']
            });
